// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: mineralos_proto/mineralos.proto

package mineralos_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the rig id.
type Payload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RigId  string  `protobuf:"bytes,1,opt,name=rig_id,json=rigId,proto3" json:"rig_id,omitempty"`
	Status *Status `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *Payload) Reset() {
	*x = Payload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mineralos_proto_mineralos_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_mineralos_proto_mineralos_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_mineralos_proto_mineralos_proto_rawDescGZIP(), []int{0}
}

func (x *Payload) GetRigId() string {
	if x != nil {
		return x.RigId
	}
	return ""
}

func (x *Payload) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Drivers *Drivers `protobuf:"bytes,1,opt,name=drivers,proto3" json:"drivers,omitempty"`
	Gpus    []*GPUS  `protobuf:"bytes,2,rep,name=gpus,proto3" json:"gpus,omitempty"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mineralos_proto_mineralos_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_mineralos_proto_mineralos_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_mineralos_proto_mineralos_proto_rawDescGZIP(), []int{1}
}

func (x *Status) GetDrivers() *Drivers {
	if x != nil {
		return x.Drivers
	}
	return nil
}

func (x *Status) GetGpus() []*GPUS {
	if x != nil {
		return x.Gpus
	}
	return nil
}

type Drivers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AMD    string `protobuf:"bytes,1,opt,name=AMD,proto3" json:"AMD,omitempty"`
	NVIDIA string `protobuf:"bytes,2,opt,name=NVIDIA,proto3" json:"NVIDIA,omitempty"`
}

func (x *Drivers) Reset() {
	*x = Drivers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mineralos_proto_mineralos_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Drivers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Drivers) ProtoMessage() {}

func (x *Drivers) ProtoReflect() protoreflect.Message {
	mi := &file_mineralos_proto_mineralos_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Drivers.ProtoReflect.Descriptor instead.
func (*Drivers) Descriptor() ([]byte, []int) {
	return file_mineralos_proto_mineralos_proto_rawDescGZIP(), []int{2}
}

func (x *Drivers) GetAMD() string {
	if x != nil {
		return x.AMD
	}
	return ""
}

func (x *Drivers) GetNVIDIA() string {
	if x != nil {
		return x.NVIDIA
	}
	return ""
}

type GPUS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GpuVendor  string `protobuf:"bytes,1,opt,name=gpu_vendor,json=gpuVendor,proto3" json:"gpu_vendor,omitempty"`
	GpuName    string `protobuf:"bytes,2,opt,name=gpu_name,json=gpuName,proto3" json:"gpu_name,omitempty"`
	MemorySize string `protobuf:"bytes,3,opt,name=memory_size,json=memorySize,proto3" json:"memory_size,omitempty"`
}

func (x *GPUS) Reset() {
	*x = GPUS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mineralos_proto_mineralos_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GPUS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUS) ProtoMessage() {}

func (x *GPUS) ProtoReflect() protoreflect.Message {
	mi := &file_mineralos_proto_mineralos_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUS.ProtoReflect.Descriptor instead.
func (*GPUS) Descriptor() ([]byte, []int) {
	return file_mineralos_proto_mineralos_proto_rawDescGZIP(), []int{3}
}

func (x *GPUS) GetGpuVendor() string {
	if x != nil {
		return x.GpuVendor
	}
	return ""
}

func (x *GPUS) GetGpuName() string {
	if x != nil {
		return x.GpuName
	}
	return ""
}

func (x *GPUS) GetMemorySize() string {
	if x != nil {
		return x.MemorySize
	}
	return ""
}

// The response message containing the greetings
type ServerReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ServerReply) Reset() {
	*x = ServerReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mineralos_proto_mineralos_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerReply) ProtoMessage() {}

func (x *ServerReply) ProtoReflect() protoreflect.Message {
	mi := &file_mineralos_proto_mineralos_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerReply.ProtoReflect.Descriptor instead.
func (*ServerReply) Descriptor() ([]byte, []int) {
	return file_mineralos_proto_mineralos_proto_rawDescGZIP(), []int{4}
}

func (x *ServerReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_mineralos_proto_mineralos_proto protoreflect.FileDescriptor

var file_mineralos_proto_mineralos_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x6f, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0f, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x6f, 0x73, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x51, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x15, 0x0a,
	0x06, 0x72, 0x69, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72,
	0x69, 0x67, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x6f, 0x73,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x67, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x32, 0x0a, 0x07, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x6f, 0x73, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x73, 0x52, 0x07, 0x64, 0x72, 0x69, 0x76,
	0x65, 0x72, 0x73, 0x12, 0x29, 0x0a, 0x04, 0x67, 0x70, 0x75, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x6f, 0x73, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x50, 0x55, 0x53, 0x52, 0x04, 0x67, 0x70, 0x75, 0x73, 0x22, 0x33,
	0x0a, 0x07, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x41, 0x4d, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x41, 0x4d, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x4e,
	0x56, 0x49, 0x44, 0x49, 0x41, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4e, 0x56, 0x49,
	0x44, 0x49, 0x41, 0x22, 0x61, 0x0a, 0x04, 0x47, 0x50, 0x55, 0x53, 0x12, 0x1d, 0x0a, 0x0a, 0x67,
	0x70, 0x75, 0x5f, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x67, 0x70, 0x75, 0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x70,
	0x75, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x70,
	0x75, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x65, 0x6d, 0x6f,
	0x72, 0x79, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x27, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32,
	0x55, 0x0a, 0x09, 0x4d, 0x69, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x6f, 0x73, 0x12, 0x48, 0x0a, 0x0c,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x2e, 0x6d,
	0x69, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x6f, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x1a, 0x1c, 0x2e, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x61, 0x6c,
	0x6f, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x61, 0x78, 0x61, 0x6d, 0x6f, 0x72, 0x65, 0x2f, 0x6d, 0x69,
	0x6e, 0x65, 0x72, 0x61, 0x6c, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x6d,
	0x69, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x6f, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mineralos_proto_mineralos_proto_rawDescOnce sync.Once
	file_mineralos_proto_mineralos_proto_rawDescData = file_mineralos_proto_mineralos_proto_rawDesc
)

func file_mineralos_proto_mineralos_proto_rawDescGZIP() []byte {
	file_mineralos_proto_mineralos_proto_rawDescOnce.Do(func() {
		file_mineralos_proto_mineralos_proto_rawDescData = protoimpl.X.CompressGZIP(file_mineralos_proto_mineralos_proto_rawDescData)
	})
	return file_mineralos_proto_mineralos_proto_rawDescData
}

var file_mineralos_proto_mineralos_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_mineralos_proto_mineralos_proto_goTypes = []interface{}{
	(*Payload)(nil),     // 0: mineralos_proto.Payload
	(*Status)(nil),      // 1: mineralos_proto.Status
	(*Drivers)(nil),     // 2: mineralos_proto.Drivers
	(*GPUS)(nil),        // 3: mineralos_proto.GPUS
	(*ServerReply)(nil), // 4: mineralos_proto.ServerReply
}
var file_mineralos_proto_mineralos_proto_depIdxs = []int32{
	1, // 0: mineralos_proto.Payload.status:type_name -> mineralos_proto.Status
	2, // 1: mineralos_proto.Status.drivers:type_name -> mineralos_proto.Drivers
	3, // 2: mineralos_proto.Status.gpus:type_name -> mineralos_proto.GPUS
	0, // 3: mineralos_proto.Mineralos.ReportStatus:input_type -> mineralos_proto.Payload
	4, // 4: mineralos_proto.Mineralos.ReportStatus:output_type -> mineralos_proto.ServerReply
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_mineralos_proto_mineralos_proto_init() }
func file_mineralos_proto_mineralos_proto_init() {
	if File_mineralos_proto_mineralos_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mineralos_proto_mineralos_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Payload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mineralos_proto_mineralos_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mineralos_proto_mineralos_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Drivers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mineralos_proto_mineralos_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GPUS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mineralos_proto_mineralos_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mineralos_proto_mineralos_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mineralos_proto_mineralos_proto_goTypes,
		DependencyIndexes: file_mineralos_proto_mineralos_proto_depIdxs,
		MessageInfos:      file_mineralos_proto_mineralos_proto_msgTypes,
	}.Build()
	File_mineralos_proto_mineralos_proto = out.File
	file_mineralos_proto_mineralos_proto_rawDesc = nil
	file_mineralos_proto_mineralos_proto_goTypes = nil
	file_mineralos_proto_mineralos_proto_depIdxs = nil
}
