version: "3.9"
services:
  frontend:
    ports:
      - 3000:3000
    build:
      context: frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
      - ./.env:/usr/src/.env
    networks:
      - mineralos-network
  backend:
    ports:
      - 5000:5000
    build:
      context: ./
      dockerfile: Dockerfile      
    volumes:
      - ./:/go/src/github.com/laxamore/mineralos
    networks:
      - mineralos-network
  mongodb:
    ports:
      - 27017:27017
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    volumes:
      - /home/laxa/mongodb/database:/data/db
    restart: unless-stopped
    networks:
      - mineralos-network

networks:
  mineralos-network:
    driver: bridge