version: "3.9"

services:

  frontend:
    ports:
      - 3000:3000
    build:
      context: frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/usr/src/app
      - ./.env:/usr/src/.env
      - ./docker_startup.sh:/usr/src/docker_startup.sh
    command: "bash ../docker_startup.sh frontend ${ENV}"
    restart: unless-stopped
    networks:
      - mineralos-network
  
  backend_api:
    ports:
      - 5000:5000
    build:
      context: ./
      dockerfile: Dockerfile      
    volumes:
      - ./:/go/src/github.com/laxamore/mineralos
    command: "sh docker_startup.sh backend_api ${ENV}"
    restart: unless-stopped
    networks:
      - mineralos-network
  
  mongodb:
    ports:
      - 27017:27017
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    volumes:
      - /home/laxa/mongodb/database:/data/db
    restart: unless-stopped
    networks:
      - mineralos-network

networks:
  mineralos-network:
    driver: bridge