version: "3.9"

services:

  frontend:
    ports:
      - 3000:3000
    build:
      context: website/
      dockerfile: Dockerfile
    volumes:
      - ./website/:/usr/src/app
      - ./.env:/usr/src/.env
      - ./docker_startup.sh:/usr/src/docker_startup.sh
    command: "bash ../docker_startup.sh website ${ENV}"
    restart: unless-stopped
    networks:
      - mineralos-network
  
  backend_api:
    ports:
      - 5000:5000
    build:
      context: ./
      dockerfile: Dockerfile      
    volumes:
      - ./:/go/src/github.com/laxamore/mineralos
    command: "sh docker_startup.sh backend_api ${ENV}"
    restart: unless-stopped
    networks:
      - mineralos-network
  
  mariadb:
    ports:
      - 3306:3306
    image: mariadb
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_USER=mineralos
      - MARIADB_PASSWORD=mineralosadmin
      - MARIADB_DATABASE=mineralos
    volumes:
      - $HOME/docker/volumes/mineralos/mariadb:/var/lib/mysql
    restart: unless-stopped
    networks:
      - mineralos-network

networks:
  mineralos-network:
    driver: bridge